version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      react:
        patterns: ["react", "react-dom", "react-router-dom"]
      eslint:
        patterns: ["eslint*"]
  - package-ecosystem: pip
    directory: /apps/engine
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
